distributedCache:
  encoding:
    mediaType: "application/x-protostream"
  persistence:
    passivation: "false"
    mongodb-store:
      connection:
        uri: "mongodb://mongo:27017/mydb"
        collection: "books"
