distributedCache:
  encoding:
    mediaType: "application/x-protostream"
  persistence:
    passivation: "false"
    mongodbStore:
      connection:
        uri: "mongodb://mongo:27017"
        collection: "books"
