distributedCache:
  encoding:
    mediaType: "application/x-protostream"
  persistence:
    passivation: "false"
    mongodb-store:
      converter: json
      connection:
        uri: "mongodb://${env.MONGODB_HOST_PORT}/mydb"
        collection: "books"
